name-template: "skat-core v$NEXT_PATCH_VERSION"
tag-template: "release/$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "documentation"
      - "test"
autolabeler:
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - '/feat/i'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'documentation'
    branch:
      - '/docs\/.+/'
      - '/doc\/.+/'
    title:
      - '/docs/i'
      - '/doc/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/chore/i'
change-template: "- $TITLE (#$NUMBER)"
template: |
  ## Changes
  $CHANGES
