name: auto-labeler

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-24.04
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
