name: daily-build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  check-outdated:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
    outputs:
      changed: ${{ steps.vars.outputs.changed }}

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: check for changes in last 24 hours
        id: vars
        run: |
          if git log --since="1 day ago" --pretty=oneline | grep .; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

  build-if-outdated:
    needs: check-outdated
    if: needs.check-outdated.outputs.changed == 'true'
    name: ${{ github.workflow }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-15, windows-2022]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: "vcpkg.json"

      - name: Run CMake+vcpkg+Ninja+CTest to build packages and generate/build/test the code.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja"
          buildPreset: "ninja/release"
          testPreset: "test/release"
