name: release-draft

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_PACKAGES }}
